[workspace]
members = [
    "console",
    "console-subscriber",
    "console-api"
]
resolver = "2"

[patch.crates-io]
tokio = { git = 'https://github.com/zaharidichev/tokio', branch = 'zd/instrument-sleep' }