[build]
  command = """
    rustup install nightly --profile minimal \
        && cargo doc --no-deps --all-features
    """
  environment = { RUSTDOCFLAGS= "--cfg docsrs -D warnings" }
  publish = "target/doc"

[[redirects]]
  from = "/"
  to = "/console-subscriber"