contact_links:
- name: ğŸ™‹ğŸ¾ Question
  url: https://github.com/tokio-rs/console/discussions/new
  about: Please use the discussions tab for questions about using the console.
- name: ğŸ”’ Report a security vulnerability
  url: https://github.com/tokio-rs/console/security/policy
  about: |
    Please review our security policy for more details on reporting a
    vulnerability.